services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "5001:5000"
    depends_on:
      - service2

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "5002:5000"
