apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: pankajmore005/service1:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: microservices-demo
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: pankajmore005/service2:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: microservices-demo
spec:
  type: NodePort
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30002
